name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine Version with GitVersion
        run: echo "VERSION=$(dotnet-gitversion /output json | jq -r '.MajorMinorPatch')" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          git config user.email "73717951+Eeshkumar45@users.noreply.github.com"
          git config user.name "Eeshkumar45"
          git tag $VERSION
          git push https://x-access-token:${{ secrets.UTILITYFEEDTOKEN }}@github.com/Eeshkumar45/UtilityFeed.git $VERSION

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build the project
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}
        working-directory: ./src

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./artifacts /p:Version=${{ env.VERSION }}
        working-directory: ./src

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
          --source "https://nuget.pkg.github.com/eeshkumar45/index.json" \
          --api-key ${{ secrets.UTILITYFEEDTOKEN }}
        working-directory: ./src
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.UTILITYFEEDTOKEN }}